apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-sqlite-pvc
  namespace: prod
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: api-env
  namespace: prod
type: Opaque
stringData:
  DATABASE_URL: "sqlite:////data/hotel.db"
